export const courses = [
  "Bachelor of Hospitality & Tourism Management",
  "Bachelor of Business Administration",
  "Post Baccalaureate Diploma in Business Management",
  "Post Baccalaureate Diploma in Supply Chain Management",
  "Post Baccalaureate Diploma in Business Analytics",
  "Post Baccalaureate Diploma in Health Care Management",
  "Post Baccalaureate Diploma in Occupational Health & Safety Management",
  "Master of Business Administration - Community Economic Development",
  "BET (Advance Standing) Post Degree - Petroleum",
  "BET (Advance Standing) Post Degree - Electronics & Controls",
  "BET (Advance Standing) Post Degree - Environmental Studies",
  "Bachelor of Science",
  "Bachelor of Health Sciences (Public Health)",
  "Bachelor of Health Sciences (Public Health) - Accelerated Post Diploma/Degree - Public Health",
  "Bachelor of Science in Human Nutrition",
  "Bachelor of Science in Nursing",
  "Diploma in Government Management",
  "Advanced Manufacturing Management - PAMFM (1 Year)",
  "Animal Care - PANCR (1 Year)",
  "Business - Accounting - PBUSA (2 Years)",
  "Business - Finance - PBUFI (2 Years)",
  "Business - Human Resources - PBUHR (2 Years)",
  "Business - Marketing - PBUMK (2 Years)",
  "Business - PBUSS (2 Years)",
  "Business Administration - Accounting - PBSAA (3 Years)",
  "Business Administration - Finance - PBAFI (3 Years)",
  "Business Administration - Human Resources - PBAHR (3 Years)",
  "Business Administration - Marketing - PBAMK (3 Years)",
  "Chemical Engineering Technology - PCETY (3 Years)",
  "Chemical Engineering Technology Environmental - PCETE (3 Years)",
  "Chemical Laboratory Technician - PCLTN (2 Years)",
  "Child and Youth Care - PCYCD (3 Years)",
  "Cloud Security - PCLSE (1 Year)",
  "Community and Justice Services - PCAJS (2 Years)",
  "Computer Engineering Technician - PCPEN (2 Years)",
  "Computer Engineering Technology - PCPET (3 Years)",
  "Computer Programming - PCPRG (2 Years)",
  "Computer Systems Technician - Information Technology Infrastructure and Services Co-op - PSITC (2 Years)",
  "Computer Systems Technician - Cyber Security - PCSCL (2 Years)",
  "Computer Systems Technology - Software Development and Network Engineering Coop - PCSSC (3 Years)",
  "Computer Systems Technology: Information Systems Engineering Co-op - PSISC (3 Years)",
  "Early Childhood Education - PECED (2 Years)",
  "Electrical Engineering Technician - PETEN (2 Years)",
  "Electrical Techniques - PETEQ (1 Year)",
  "Electromechanical Engineering Technician - PELTN (2 Years)",
  "Electromechanical Engineering Technology - PEMTY (3 Years)",
  "Environmental Control - PENCT (1 Year)",
  "Environmental Technician - PENST (2 Years)",
  "Honours Bachelor of Information Sciences (Cyber Security) â€“ PBAIS (4 Years)",
  "Internet Communications Technology Coop - PICTC (3 Years)",
  "Internet of Things and Machine Intelligence - PIOTM (1 Year)",
  "Mechanical Engineering Technician - PMETN (2 Years)",
  "Mechanical Engineering Technician Drafting - PMETD (2 Years)",
  "Mechanical Engineering Technology - PMETY (3 Years)",
  "Mechanical Engineering Technology Design and Drafting - PMEDD (3 Years)",
  "Mechanical Technician - Tool Making - PMTTM (2 Years)",
  "Mechanical Techniques - Plumbing - PLUMB (1 Year)",
  "Mechanical Techniques - CNC & Precision Machining (1 Year)",
  "Paralegal - PARAL (2 Years)",
  "Pharmacy Technician - PPHTO (2 Years)",
  "Police Foundations - PPOLF (2 Years)",
  "Practical Nursing - PPNSG (2 Years)",
  "Pre-Health Sciences Pathway to Advanced Diplomas and Degrees - PPHSS (1 Year)",
  "Quality Assurance Manufacturing and Management - PQUAS (1 Year)",
  "Social Service Worker - Gerontology - PSSWG (2 Years)",
  "Social Service Worker - PSSWK (2 Years)",
  "Advertising - Account Management Coop - PADAC (1 Year)",
  "Advertising and Marketing Communications - PADMK (2 Years)",
  "Advertising and Marketing Communications Management - PAMCM (3 Years)",
  "Architectural Technician - PATCN (2 Years)",
  "Architectural Technology - PARTY (3 Years)",
  "Business Analysis and Process Management - PBAPM (1 Year)",
  "Creative Industries Management - PCRIM (1 Year)",
  "General Arts and Science - PGASU (2 Years)",
  "General Arts and Science University 1 Year - PGAUC (1 Year)",
  "Honours Bachelor of Business Administration (Accounting) - PBACC (4 Years)",
  "Honours Bachelor of Business Administration (Finance) - PBBAF (4 Years)",
  "Honours Bachelor of Business Administration (Human Resources Management) - PBHRM (4 Years)",
  "Honours Bachelor of Business Administration (Marketing Management) - PBBAM (4 Years)",
  "Honours Bachelor of Business Administration (Supply Chain Management) - PBSCM (4 Years)",
  "Human Resources Management Coop - PHRMC (1 Year)",
  "Interior Decorating - PINDE (2 Years)",
  "Marketing Management Coop - PMKMC (1 Year)",
  "Office Administration - Executive - POFAE (2 Years)",
  "Office Administration - Health Services - POAHS (2 Years)",
  "Professional Accounting - PPACG (1 Year)",
  "Professional Accounting Coop - PPACGC (1 Year)",
  "Project Management - PPRJM (1 Year)",
  "Urban Design - PURBN (1 Year)",
  "Advanced Special Effects Makeup Prosthetics and Props - PASEM (1 Year)",
  "Art Fundamentals - PARTF (1 Year)",
  "Honours Bachelor of Computer Science (Mobile Computing) - PBACS (4 Years)",
  "Honours Bachelor of Computer Science (Specialty in Cloud Computing) - PBCPCC (4 Years)",
  "Honours Bachelor of Computer Science (Specialty in Data Analytics) - PBCPDA (4 Years)",
  "Honours Bachelor of Computer Science (Specialty in Data Engineering) - PBCPDE (4 Years)",
  "Honours Bachelor of Computer Science (Specialty in Game Engineering) - PBCPGE (4 Years)",
  "Honours Bachelor of Computer Science (Specialty in Network Engineering) - PBCPNN (4 Years)",
  "Makeup for Media and Creative Arts - PMMCA (2 Years)",
  "Media Fundamentals - PMDAF (1 Year)",
  "Public Relations - Corporate Communications - PPRCC (1 Year)",
  "Business Certificate",
  "Continuing Care Assistant",
  "Early Childhood Education Diploma",
  "Early Childhood Education Certificate",
  "Global Business Management Post Graduate Certificate",
  "Certificate in Adult Education",
  "Leadership in Community-Based Education",
  "Consecutive Admission to CCES and LCBE",
  "Certificate in Outdoor Recreation",
  "Certificate in Recreation and Leisure Studies",
  "Certificate in Arts Management",
  "Certificate in Canada's Cultural Context",
  "Certificate in Choral/Vocal Music",
  "Certificate in Digital Media",
  "Certificate in Instrumental Music",
  "Certificate in Digital Ethics",
  "BA-Arts & Culture-School of Fine & Performing Arts",
  "BA in Adult Education as a First Degree (Hons.)",
  "Bachelor of Arts - Community Health Three Year",
  "Bachelor of Arts in Applied Linguistics",
  "BA in Adult Education - Subsequent Degree (Hons.)",
  "Certificate in Canadian Culture and Diversity",
  "Certificate in Public Policy and Administration",
  "Bachelor of Arts - Critical Criminology",
  "Bachelor of Science - Biophysics",
  "Certificate in Language & Culture Proficiency",
  "Cert in Language Proficiency for Native Speakers",
  "Certificate in Arts & Culture Studies",
  "Introductory Cert. in Ancient Greek & Latin Lang.",
  "Enhanced Cert. in Ancient Greek & Latin Language",
  "Certificate in Business French and Translation",
  "Bachelor of Computing and Business",
  "Certificate in Women's and Gender Studies",
  "Certificate in Education and Applied Theatre",
  "Certificate-Teaching English-Second/Foreign Lang.",
  "Bachelor of Science - Biochemistry",
  "Certificate in Labour Studies",
  "Certificate in Public Law",
  "Certificate in Grape & Wine Technology",
  "Certificate in Studies in Rhetoric & Prof Writing",
  "Bachelor of Arts - Child and Youth Studies",
  "Bachelor of Business Economics",
  "Bachelor of Arts - Economics",
  "Bachelor of Science - Environmental Geosciences",
  "Bachelor of Arts - English Language & Literature",
  "BASc Earth & Planetary Science Communications",
  "Bachelor of Arts in Educational Studies",
  "Certificate in Ethics",
  "Bachelor of Arts - Film Studies",
  "BSc Data Science & Analytics - Financial Analytics",
  "BA Forensic Psychology and Criminal Justice",
  "Certificate in Film Studies",
  "Bachelor of Science - Computer Science",
  "Bachelor of Arts - Geography",
  "Bachelor of Science - Mathematics & Statistics",
  "Bachelor of Arts - History",
  "Bachelor of Child Health",
  "Certificate in Speech, Language & Hearing Sciences",
  "Bachelor of Arts - General Humanities",
  "Bachelor of Science - Sciences",
  "Bachelor of Science - Biomedical Sciences",
  "Bachelor of Science - Neuroscience",
  "Bachelor of Arts - Interactive Arts and Science",
  "Bachelor of Science - Biotechnology",
  "BSc Math & Statistics - Accelerated Math Studies",
  "Bachelor of Science - Chemistry",
  "Bachelor of Science - Physics",
  "Bachelor of Accounting",
  "Bachelor of Arts - Canadian Studies",
  "Bachelor of Arts - Modern Languages",
  "Bachelor of Arts - Labour Studies",
  "Bachelor of Music - School of Fine & Performing Arts",
  "Bachelor of Arts with a Major in Music",
  "BA - Medieval & Renaissance Studies",
  "Bachelor of Engineering, Integrated Engineering",
  "Bachelor of Science - Geography",
  "Bachelor of Science - Oenology & Viticulture",
  "Bachelor of Physical Education",
  "Bachelor of Arts - Popular Culture",
  "Bachelor of Arts - Philosophy",
  "Bachelor of Kinesiology",
  "Certificate in Pre-Law",
  "Bachelor of Arts - Political Science",
  "Bachelor of Public Health",
  "Bachelor of Arts - Psychology",
  "Bachelor of Arts - Classics",
  "BA - Visual Arts",
  "Bachelor of Science - Biological Sciences",
  "BSc Data Science & Analytics - Computational Data Sci",
  "Bachelor of Science in Medical Sciences",
  "Bachelor of Science - Kinesiology",
  "Bachelor of Sport Management",
  "Bachelor of Arts - Sociology",
  "BSc Psychology",
  "Bachelor of Arts - Social Sciences",
  "BA Dramatic Arts - School of Fine & Performing Arts",
  "Bachelor of Tourism and Environment",
  "Bachelor of Arts - Media and Communication Studies",
  "Bachelor of Arts - Business Communication Studies",
   "Bachelor of Recreation and Leisure Studies",
  "Certificate in Creative Writing",
  "Bachelor of Arts - Women's and Gender Studies",
  "Bachelor of Science - Earth Sciences",
  "Bachelor of Computing and Business - Co-op",
  "Bachelor of Business Economics - Co-op",
  "Bachelor of Arts - Economics - Co-op",
  "BSc - Environmental Geosciences - Co-op",
  "BSc Data Science & Analytics - Financial Analytics Co-op",
  "Bachelor of Science - Computer Science - Co-op",
  "Bachelor of Arts - Geography - Co-op",
  "Bachelor of Science - Mathematics & Statistics Co-op",
  "Bachelor of Science - Combined Math/Comp Sci - Co-op",
  "Bachelor of Science - Chemistry - Co-op Program",
  "Bachelor of Accounting - Co-op",
  "Bachelor of Arts - Labour Studies - Co-op",
  "Bachelor of Business Administration - Co-op",
  "Bachelor of Engineering, Integrated Engineer - Co-op",
  "Bachelor of Science - Geography - Co-Op",
  "Bachelor of Science - Oenology & Viticulture - Co-op",
  "Bachelor of Arts - Political Science - Co-op",
  "Bachelor of Public Health - Co-op",
  "Bachelor of Arts - Psychology - Co-op",
  "BSc Data Sci & Analyt - Computational Data Sci - Co-op",
  "BSc Psychology - Co-op",
  "BA Dramatic Arts, Fine & Performing Arts",
  "Bachelor of Arts - Tourism and Environment",
  "MBA",
  "Master of Education",
  "African Studies (Global Development Studies B.A.) Specialization",
  "Ancient Greek & Roman Studies (Honours Arts)",
  "Anthropology (Honours Science)",
  "Anthropology - Biological Anthropology (Honours Science)",
  "Anthropology & Forensics (Honours Arts)",
  "Anthropology & Forensics (Honours Science)",
  "Archaeology (Honours Arts)",
  "Archaeology - Environmental Archaeology (Honours Arts)",
  "Archaeology (Honours Science)",
  "Archaeology - Environmental Archaeology (Honours Science)",
  "Archaeology - Mediterranean Archaeology",
  "Arts (Honours Arts)",
  "Bachelor of Arts & Science",
  "Biochemistry & Molecular Biology (Honours Science)",
  "Biology (Honours Science)",
  "Biomedical Science (Honours Science)",
  "Business Administration (BBA)",
  "Business Administration (BBA) - Accounting",
  "Business Administration (BBA) - Economics",
  "Business Administration (BBA) - Entrepreneurship",
  "Business Administration (BBA) - Ethics & Sustainability",
  "Business Administration (BBA) - Finance",
  "Business Administration (BBA) - Human Resources Management",
  "Business Administration (BBA) - Information Systems & E-Commerce",
  "Business Administration (BBA) - Marketing & Consumer Culture",
  "Business Administration (BBA) - Niigaaniiwin The Art of Leading",
  "Business & Arts (Honours Arts)",
  "Business & Science (Honours Science)",
  "Canadian Studies (Honours Arts)",
  "Chemical Physics (Honours Science)",
  "Chemistry (Honours Science)",
  "Computer Science (Honours Science)",
  "Computer Science - Computer Science (Honours Science)",
  "Computer Science - Data Analytics (Honours Science)",
  "Computer Science - Software Engineering (Honours Science)",
  "Computing Systems & Business (Honours Arts)",
  "Computing Systems & Economics (Honours Arts)",
  "Computing Systems & Media Studies (Honours Arts)",
  "Computer Science & Physics (Honours Science)",
  "Cultural Studies (Honours Arts)",
  "Cultural Studies & Business (Honours Arts)",
  "Culture & Theory (Cultural Studies B.A.) Specialization",
  "Economics (Honours Arts)",
  "Economics (Honours Science)",
  "Economics & Business (Honours Arts)",
  "English & Business (Honours Arts)",
  "English Literature (Honours Arts)",
  "English Literature (Honours Arts) - Literary History",
  "English Literature (Honours Arts) - Racial and Social Justice",
  "Environmental & Resource Science (Honours Science)",
  "Environmental & Resource Studies (Honours Arts)",
  "Environmental & Resource Studies and Business (Honours Arts)",
  "Environmental Chemistry (Honours Science)",
  "Environmental Geoscience (Honours Science)",
  "Environmental Science/Studies (Honours)",
  "Environmental Science (Honours Science) - Climate Change Science & Policy",
  "Environmental Studies (Honours Arts) - Climate Change Science & Policy",
  "Film & Media (Cultural Studies B.A.) Specialization",
  "Financial Science (B.Sc.)",
  "Forensics & Arts (Honours Arts)",
  "Forensics & Arts (Honours Arts) - Law & Policing Specialization",
  "Forensics & Business (Honours Arts)",
  "Forensics & Science (Honours Science)",
  "Forensics & Science (Honours Science) - Law & Policing Specialization",
  "French & Francophone Studies (Honours Arts)",
  "French & Francophone Studies (Honours Arts) - French Writing",
  "Gender & Social Justice (Honours Arts)",
  "Gender & Social Justice (Honours Arts) - Feminist Studies",
  "Gender & Social Justice B.A. (Honours Arts) - Sexuality Studies",
  "Geography (Honours Arts)",
  "Geography (Honours Arts) - Climate Change Science & Policy",
  "Geography (Honours Science)",
  "Geography (Honours Science) - Climate Change Science & Policy",
  "Global Migration & Refugee Studies (Global Development Studies B.A.) Specialization",
  "Greek & Latin (Ancient Greek & Roman Studies B.A.) Specialization",
  "Health Sciences (Biology B.Sc.) Specialization",
  "Health Studies (Sociology B.A.) Specialization",
  "History (Honours Arts)",
  "History & Business (Honours Arts)",
  "Indigenous Environmental Science (Honours Science)",
  "Indigenous Environmental Studies (Honours Arts)",
  "Indigenous Studies (Honours Arts)",
  "Indigenous Studies - Applied Indigenous Knowledge (Honours Arts) Specialization",
  "Indigenous Studies - Indigenous Performance (Honours Arts) Specialization",
  "Indigenous Studies - Nishinaabemowin (Honours Arts) Specialization",
  "Indigenous Studies & Business (Honours Arts)",
  "Information Systems (Honours Arts)",
  "Information Systems & Business (Honours Arts)",
  "Information Systems & Science (Honours Science)",
  "Integrated Arts (Cultural Studies B.A.) Specialization",
  "Global Development & Business (Honours Arts)",
  "Global Development Studies (Honours Arts)",
  "International Development Studies (Honours Arts) - Latin American Studies",
  "International Political Economy (Honours Arts)",
  "Literature & Narrative (Cultural Studies B.A.) Specialization",
  "Mathematical Economics (Honours Science)",
  "Mathematical Physics (Honours Science)",
  "Mathematics (Honours Science)",
  "Mathematics (Honours Science) - Statistics Specialization",
  "Mathematics - Mathematical Finance (Honours Science)",
  "Media Studies (Honours Arts)",
  "Media Studies & Business (Honours Arts)",
  "Philosophy (Honours Arts)",
  "Philosophy - Ethics Specialization (Honours Arts)",
  "Philosophy & Business (Honours Arts)",
  "Physics (Honours Science)",
  "Political Studies (Honours Arts)",
  "Political Studies (Honours Arts) - Legal Studies Option",
  "Political Studies - Public Policy (Honours Arts)",
  "Political Studies & Business (Honours Arts)",
  "Political Studies & Forensics (Honours Arts)",
  "Political Studies B.A. (Honours Arts) - Political Theory",
  "Political Studies B.A. (Honours Arts) - World Politics",
  "Psychological Development (Honours Arts) Specialization",
  "Psychological Development (Honours Science) Specialization",
  "Psychology (Honours Arts)",
  "Psychology (Honours Science)",
  "Psychology (Honours Science) - Health & Well-being",
  "Psychology & Business (Honours Arts)",
  "Psychology & Business (Honours Science)",
  "Psychology & Economics (Honours Arts)",
  "Psychology & Forensics (Honours Arts)",
  "Psychology & Forensics (Honours Science)",
  "Quebec & Franco-Canadian Studies (French & Francophone Studies B.A.) Specialization",
  "Science (Honours Science)",
  "Social Work (BSW)",
  "Sociology (Honours Arts)",
  "Sociology - Social Justice & Equity Studies",
  "Sociology - Socio-Legal Studies",
  "Sociology & Business (Honours Arts)",
  "Sustainable Agriculture & Food Systems (Honours Arts)",
  "Sustainable Agriculture & Food Systems (Honours Arts) - Small-scale Farming",
  "Sustainable Agriculture & Food Systems (Honours Science)",
  "Sustainable Agriculture & Food Systems (Honours Science) - Small-scale Farming",
  "Anthropology (Honours Arts)",
  "Anthropology & Psychology (Honours Arts)",
  "Anthropology & Sociology (Honours Arts)",
  "Arts & Business (Honours Arts)",
  "Business (BBA) - Communications Option",
  "Child & Youth Studies (Honours Arts)",
  "Child & Youth Studies and Psychology (Honours Arts)",
  "Child & Youth Studies and Sociology (Honours Arts)",
  "Communications (Honours Arts)",
  "Communications - Business Communications",
  "Communications - Media Relations",
  "Computing Systems (General Arts)",
  "Computer Science (General Science)",
  "English Literature & Business (Honours Arts)",
  "English Literature & Media Studies (Honours Arts)",
  "English Literature & Psychology (Honours Arts)",
  "English Literature & Sociology (Honours Arts)",
  "Gender & Social Justice (General Arts)",
  "Information Systems & Media Studies (Honours Arts)",
  "Media Studies & Psychology (Honours Arts)",
  "Philosophy (General Arts)",
  "Policing & Community Well-Being",
  "Psychology (Honours Arts) - Health & Well-being",
  "Psychology (Honours Arts) - Psychological Development",
  "Psychology (Honours Science) - Psychological Development",
  "Psychology & Sociology (Honours Arts)",
  "Science & Business (Honours Science)",
  "Human Resource Management & Business Communication - Dual Post-Graduate Certificate (Durham)",
  "Human Resources, Marketing & Entrepreneurship - Dual Post-Graduate Certificate (Durham)",
  "Accounting - Post-Graduate Certificate",
  "Finance - Post-Graduate Certificate",
  "Human Resources, Marketing & Entrepreneurship - Dual Post-Graduate Certificate",
  "Master of Management",
  "Master of Management Strategic Change Management",
  "3D Modelling and Visual Effects Production",
  "Accounting, Bachelor of Commerce",
  "Accounting, Business",
  "Accounting, Business Administration",
  "Accounting, Professional Practice",
  "Addictions and Mental Health",
  "Advertising & Graphic Design",
  "Advertising - Media Management",
  "Advertising and Marketing Communications",
  "Alternative Dispute Resolution",
  "Architectural Technology",
  "Artificial Intelligence with Machine Learning",
  "Baking and Pastry Arts Management",
  "Biotechnology",
  "Broadcast Television/Videography",
  "Building Construction Technician",
  "Business Administration",
  "Business Insights and Analytics",
  "Business Management",
  "Carpentry and Renovation Technician",
  "Carpentry and Renovation Techniques",
  "Child and Youth Care",
  "Civil Engineering Technology",
  "Cloud Computing",
  "Community and Justice Services",
  "Computer Engineering Technology",
  "Computer Programming",
  "Computer Programming and Analysis",
  "Computer Systems Technician – Information Technology Infrastructure and Services",
  "Construction Engineering Technology",
  "Content Strategy",
  "Cosmetic Management",
  "Culinary Management",
  "Culinary Skills",
  "Design Foundation",
  "Digital Business Management, Bachelor of Commerce",
  "Early Childhood Education",
  "Electrical Engineering Technician - Control Systems",
  "Electrical Engineering Technology - Control Systems",
  "Electrical Techniques",
  "Electromechanical Engineering Technician",
  "Electromechanical Engineering Technology",
  "Electronics Engineering Technician",
  "Electronics Engineering Technology",
  "Emergency Telecommunications",
  "Enterprise Software Development",
  "Entrepreneurial Enterprise, Business Management",
  "Esthetician/Spa Management",
  "Event Management",
  "Fashion Arts and Business",
  "Fashion Management",
  "Fashion Management, Bachelor of Commerce",
  "Finance, Bachelor of Commerce",
  "Financial Planning",
  "Financial Services, Business Management",
  "Fitness and Health Promotion",
  "Furniture and Cabinetmaking Techniques",
  "Game Programming",
  "General Arts and Science - Technology",
  "Global Business Management",
  "Graphic Design",
  "Graphic Design for Print and Web",
  "Healthcare Management, Bachelor of Commerce",
  "Heating, Refrigeration and Air Conditioning Technician",
  "Heating, Refrigeration and Air Conditioning Technology",
  "Hospitality - Hotel and Restaurant Operations Management",
  "Hospitality and Tourism Operations Management",
  "Human Resources Management",
  "Human Resources Management, Bachelor of Commerce",
  "Industrial Woodworking Technician",
  "Information Technology Solutions",
  "Interior Decorating",
  "International Business, Bachelor of Commerce",
  "International Development",
  "Law Clerk",
  "Management Studies, Bachelor of Commerce",
  "Marketing Management",
  "Marketing, Bachelor of Commerce",
  "Marketing, Business",
  "Massage Therapy",
  "Mechanical Engineering Technician",
  "Mechanical Engineering Technology",
  "Mechanical Techniques - Millwright",
  "Media Communications",
  "Multimedia Design and Development",
  "Paralegal",
  "Paralegal Education",
  "Pharmacy Technician",
  "Plumbing Techniques",
  "Police Foundations",
  "Practical Nursing",
  "Professional Writing and Communications",
  "Project Management",
  "Protection, Security and Investigation",
  "Public Relations (Graduate Certificate)",
  "Regulatory Affairs",
  "Research Analyst",
  "Social Service Worker",
  "Sport Management",
  "Supply Chain Management",
  "Supply Chain Management, Bachelor of Commerce",
  "Tourism - Travel Services Management",
  "User Experience (UX) Design",
  "Virtual Production NEW",
  "Web Design and Development",
  "Web Development",
  "Wireless Telecommunications",
  "Associate of Arts Degree",
  "Associate of Arts Degree - Creative Writing",
  "Associate of Arts Degree - English",
  "Associate of Arts Degree - Psychology",
  "Bachelor of Arts with a Major in Interdisciplinary Studies",
  "Bachelor of Arts with a Major in Psychology",
  "Bachelor of Science - General",
  "Associate of Science Degree",
  "Associate of Science Degree - Biology",
  "Bachelor of Business Administration Degree",
  "Business Administration Diploma",
  "Business Administration Certificate",
  "Communication Studies Diploma",
  "Bachelor of Communication Studies Degree",
  "North American Business Management Applied Post-Baccalaureate Diploma",
  "North American Business Management Post-Baccalaureate Diploma",
  "Bachelor of Tourism Management Degree",
  "Tourism Management Co-operative Education Diploma",
  "Diploma in Tourism Management International",
  "Global Hospitality and Tourism Management Post - Post-Baccalaureate Diploma",
  "Automotive Collision and Refinishing Diploma",
  "Automotive Service Technology Diploma",
  "Heavy Mechanical Technology",
  "Automotive Parts and Service Management",
  "Accounting Diploma",
  "Cosmetology Diploma",
  "Culinary Art Diploma",
  "CAD & BIM Technology Diploma",
  "Computer System Technology Diploma",
  "Dental Technology Science Diploma",
  "Electronics Repair Technology Diploma",
  "Early Childhood Care and Education Diploma",
  "Marketing Technology Diploma",
  "Optician Diploma",
  "Health Care Assistant",
  "Hospitality Management Diploma",
  "Occupational and Physical Therapy Assistant Diploma",
  "Music Diploma",
  "Dance Diploma",
  "Fashion Design and Production Diploma",
  "Graphic Designing Diploma",
  "Jewellery Art and Design Diploma",
  "PG Diploma Business and Project Management",
  "PG Diploma Business Management",
  "Post Graduate Diploma in Hospitality Management",
  "PG Diploma in Network Technology Administration & Security",
  "PG Diploma in Cybersecurity",
  "University Transfer- Arts",
  "University Transfer- Science",
  "University Transfer- Computing Science",
  "University Transfer- Engineering",
  "Associate of Science- Computer Science Pathway",
  "Bachelor of Applied Music",
  "Bachelor of Hospitality Management",
  "Administrative Professional",
  "Artisan Baking Certificate",
  "Asian Culinary Certificate",
  "Baking and Pastry Arts - Artisan Baking & Pastry Dual Certificates",
  "Esthetics & Spa Therapy",
  "Hairstylist Certificate",
  "Legal Administration Assistant Certificate",
  "Medical Office Assistant",
  "Medical Transcriptionist",
  "3D Computer Animation",
  "Advanced CNC Manufacturing",
  "Agri-Business Management",
  "Animation",
  "Applied Artificial Intelligence & Machine Learning (Optional Co-op)",
  "Applied Electrical Motion and Control Management",
  "Applied Electrical Motion and Control Management - Automotive",
  "Applied Electrical Motion and Control Management - Logistical Automation",
  "Applied Energy Management",
  "Applied Energy Management- Renewable Energy",
  "Applied Energy Management - Energy Systems Control",
  "Applied Energy Management - Residential & Commercial",
  "Applied Manufacturing Management - Automation",
  "Applied Manufacturing Management - Design Integration - Aerospace Stream",
  "Applied Manufacturing Management - Design Integration - Electronics Manufacturing",
  "3D Computer Animation",
  "Applied Manufacturing Management - Design Integration 3D Printing",
  "Applied Manufacturing Management - Design Integration- Aerospace Stream",
  "Applied Manufacturing Management - Machining",
  "Applied Manufacturing Management - Welding",
  "Applied Network Infrastructure and System Administration",
  "Applied Research",
  "Bachelor of Applied Biotechnology (Honours)",
  "Bachelor of Business Administration (Honours)- Accounting, Audit and Information Technology",
  "Bachelor of Business Administration (Honours)- International Business Management",
  "Bachelor of Computer Science",
  "Bachelor of Computer Science (Honours)",
  "Bachelor of Applied Health Information Science",
  "Bachelor of Applied Technology (Honours) - Architecture - Project and Facility Management",
  "Bachelor of Commerce (Honours) Financial Services",
  "Bachelor of Communication Management",
  "Bachelor of Community and Criminal Justice",
  "Bachelor of Design (Honours)",
  "Sport Management",
  "Supply Chain Management",
  "Supply Chain Management, Bachelor of Commerce",
  "Tourism - Travel Services Management",
  "User Experience (UX) Design",
"Bachelor of Early Learning Program Development",
  "Bachelor of Engineering - Building Systems Engineering",
  "Bachelor of Engineering - Power Systems Engineering",
  "Bachelor of Engineering - Sustainable Design Engineering",
  "Bachelor of Engineering - Power System Engineering",
  "Bachelor of Engineering - Mechanical System Engineering",
  "Bachelor of Engineering - Cyber System Engineering",
  "Bachelor of Environmental Public Health (Honours)",
  "Bachelor of Human Resource Management",
  "Bachelor of Interior Design (Honours)",
  "Baking and Pastry Arts",
  "Big Data Solution Architecture (Optional Co-op)",
  "Biotechnology Technician Fast Track",
  "Bookkeeping",
  "Broadcasting - Television and Independent Production",
  "Broadcasting Performance and Digital Media",
  "Business",
  "Business - Finance",
  "Business - Insurance",
  "Business - International Business",
  "Business - Marketing",
  "Business - Purchasing",
  "Business - Supply Chain and Operations for Commercial Trucking",
  "Business Administration - Accounting",
  "Business Administration - Financial Planning",
  "Business Administration - Management",
  "Business Administration - Marketing",
  "Business Analytics",
  "Business Development and Sales",
  "Broadcast - Radio",
  "Career Development Professional",
  "Clinical Research",
  "Charcuterie and Artisanal Foods",
  "Civil Engineering Technician",
  "Climate Change Mitigation",
  "Cloud Data Management",
  "Cloud Development and Operations",
  "Community Settlement Services",
  "Community Pharmacy Assistant",
  "Computer Animation & Motion Graphics",
  "Computer Applications Development (Optional Co-op)",
  "Computer System Technician - Informative Technology Infrastructure and Services",
  "Computer-Aided Drafting & Design",
  "Construction Management",
  "Computer Application Security",
  "Construction Engineering Technology - Architecture",
  "Construction Techniques - Brick and Stone",
  "Construction Techniques (Welding, HVAC, Plumbing and Masonry)",
  "Cybersecurity Response Planning",
  "Data Processing and Reporting",
  "Design Foundations",
  "Design Solution Management",
  "Digital Solutions Management (Optional Co-op)",
  "Drafting and Design for Additive Manufacturing",
  "Educational Support",
  "Electrical Engineering Technician",
  "Electrical Engineering Technician - Industrial",
  "Enhanced Practice for Internationally Educated Nurses",
  "Esthetician",
  "Electro Mechanical and Automation Maintenance",
  "Embedded Systems Development",
  "Energy Systems Engineering Technology - Electrical",
  "English for Academic Studies",
  "Environmental Building Sciences",
  "Environmental Engineering Applications",
  "Esports Marketing and Event Management",
  "Esports and Event Media Production",
  "Financial Planning Services",
  "Financial Technology",
  "Fitness Health Promotion",
  "Food Processing Technician",
  "Food Safety Quality Assurance - Food Processing",
  "Food and Beverage Management - Hotel and Restaurant Operations",
  "Fraud Investigation and Risk Management",
  "Game - Design",
  "Game - Art",
  "General Arts and Science - Diploma Option",
  "General Arts and Science - One Year",
  "Global Hospitality Management",
  "Global Public Health Management",
  "Health Care Administration and Service Management",
  "Health Care Administration Management (Nursing Leadership Stream)",
  "Health Care Quality Improvement and Safety Management",
  "Health Office Administration",
  "Health and Social Systems Navigation",
  "Healthcare Project Leadership and Management",
  "Hospitality Operations - Food and Beverage",
  "Human Factors and Ergonomics",
  "Human Resource Management",
  "Human Service Foundation",
  "IT Innovation and Design",
  "Information Technology Business Analysis",
  "Information Technology Network Security",
  "Information Technology Project Management",
  "Interactive Media Management - Interaction Design",
  "Journalism",
  "Laboratory Quality Management",
  "Long Term Care and Retirement Community Management",
  "Machining for Manufacturing",
  "Management and Leadership Development",
  "Management in Community Services",
  "Manufacturing Engineering Technology - Welding and Robotics",
  "Mechanical Engineering Technician - Automated Manufacturing",
  "Mechanical Engineering Technology - Automated Manufacturing",
  "Mechanical Engineering Technology - Design and Analysis",
  "Mechanical Engineering Technology - Robotics and Automation",
  "Mechanical Technician - CNC",
  "Media Foundations",
  "Medical Office Practices",
  "Mental Health and Substance Use",
  "Mobile Solutions Development (Optional Co-op)",
  "Mobile and Web Development",
  "Motive Power Fundamentals - Automotive Repair",
  "Motive Power Technician - Automotive Service",
  "Motive Power Technician - Heavy Duty Equipment",
  "Motive Power Technician - Truck and Coach",
  "Nursing Leadership and Healthcare Management",
  "Nutrition and Food Services Management",
  "Occupational Health, Safety and Wellness",
  "Office Administration - Executive",
  "Office Administration - Legal",
  "Packaging Engineering Technician",
  "Payroll and Bookkeeping",
  "Pre-Health Sciences Pathway to Certificates and Diplomas",
  "Pre-Service Firefighter Education and Training",
  "Predictive Analytics",
  "Process Quality Engineering",
  "Public Relations",
  "Quality Assurance - Manufacturing and Management",
  "Renewable Energy Techniques",
  "Reporting Systems and Database Development",
  "Robotics and Industrial Automation",
  "Social Media Marketing",
  "Software Engineering Technician",
  "Software Engineering Technology",
  "Software Quality Assurance and Test Engineering (Optional Co-op)",
  "Strategic Global Business Management",
  "Strategic Marketing Communication",
  "Strategic Marketing and Research Analysis",
  "Structural Packaging Design and Management",
  "Structural Steel Management and Detailing",
  "Supply Chain Management - Global",
  "Sustainable Business Management",
  "Sustainable Waste Management",
  "Technical Communication",
"Tourism - Destinations and Travel Management",
"Urban Planning and GIS",
"Technical Systems Analysis",
"Virtual Reality Production",
"Virtualization and Cloud Computing",
"Visual Merchandising Arts",
"Web Development and Internet Applications Fundamentals",
"Welding Engineering Technician - Robotics",
"Welding Engineering Technician - Inspection",
"Welding and Fabrication Technician",
"Wireless Network Infrastructure",
"Woodworking Technician",
"Community Pharmacy Assistant",
"Network Technical Support",
"Real Estate Development and Management",
"Advertising and Marketing Communications (AMC) Kingston",
"Bachelor of Business Administration (BBA) Kingston",
"Bachelor of Science (Nursing) Brockville",
"Bachelor of Science (Nursing) Cornwall",
"Biotechnology Advanced Kingston",
"Business Kingston",
"Business Brockville",
"Business Cornwall",
"Business Accounting Kingston",
"Business Accounting Cornwall",
"Business Administration - Cornwall",
"Business Administration - Accounting Kingston",
"Pre-Health Science Pathway to Advanced Diplomas and Degrees (Cornwall)",
"Business Administration - Human Resources Kingston",
"Business Administration Marketing Kingston",
"Business Analytics - Academic and Professional Success in Canada Kingston",
"Business Human Resources",
"Business Marketing Kingston",
"Child and Youth Care Kingston",
"Civil Engineering Technology Kingston",
"Computer Programming Cornwall",
"Computer Programming and Analysis Kingston",
"Computer Systems Technician Kingston",
"Computer Systems Technician Cornwall",
"Culinary Management Kingston",
"Cybersecurity Kingston",
"Digital Marketing Communications (DMC) Kingston",
"Electrical Engineering Technician (Kingston)",
"Early Childhood Education Kingston",
"Early Childhood Education Cornwall",
"Energy Systems Engineering Technician Kingston",
"Fitness and Health Promotion Kingston",
"Game Programming Cornwall",
"General Arts & Science Kingston",
"General Arts & Science General Stream Cornwall",
"General Arts & Science Cornwall",
"Graphic Design Kingston",
"Hairstyling (Accelerated) Kingston",
"Health Information Management Kingston",
"Hospitality Kingston",
"Human Resource Management Kingston",
"Health Care Administration Kingston",
"Instrumentation and Control Engineering Technology Cornwall",
"Instrumentation and Control Engineering Technology Kingston",
"Law Clerk Kingston",
"Mechanical Technician Kingston",
"Mental Wellness and Addictions Worker Brockville",
"Music & Digital Media Kingston",
"Music Theatre - Performance Brockville",
"Office Administration Health Services Kingston",
"Office Administration Legal Kingston",
"Office Administration Health Services Brockville",
"Personal Support Worker Brockville",
"Police Foundations Cornwall",
"Project Management Kingston",
"Project Management Cornwall",
"Social Service Worker Cornwall",
"Supply Chain Management Cornwall",
"Therapeutic Recreation Kingston",
"Tourism Kingston",
"User Experience Design (UX Design) Kingston",
"Wind Turbine Technician Kingston",
"Visual & Creative Arts - Fine Arts Brockville",
"Bachelor of Business Administration (BBA)",
"Master of Business Administration (MBA)",
"Bachelor of Commerce (B.Com)",
"Master of Commerce (M.Com)",
"Bachelor of Finance",
"Master of Finance (MFin)",
"Bachelor of Accounting",
"Master of Accounting (MAcc)",
"Bachelor of Marketing",
"Master of Marketing (MMktg)",
"Bachelor of International Business",
"Master of International Business",
"Bachelor of Entrepreneurship",
"Master of Entrepreneurship",
"Bachelor of Human Resource Management",
"Master of Human Resource Management",
"Bachelor of Supply Chain Management",
"Master of Supply Chain Management",
"Bachelor of Economics",
"Master of Economics",
"Bachelor of Business Analytics",
"Master of Business Analytics",
"Bachelor of Operations Management",
"Master of Operations Management",
"Bachelor of Event Management",
"Master of Event Management",
"Bachelor of Retail Management",
"Master of Retail Management",
"Bachelor of Hospitality Management",
"Master of Hospitality Management",
"Bachelor of Mechanical Engineering (B.Eng)",
"Master of Mechanical Engineering (M.Eng)",
"Bachelor of Civil Engineering",
"Master of Civil Engineering",
"Bachelor of Electrical Engineering",
"Master of Electrical Engineering",
"Bachelor of Computer Engineering",
"Master of Computer Engineering",
"Bachelor of Aerospace Engineering",
"Master of Aerospace Engineering",
"Bachelor of Biomedical Engineering",
"Master of Biomedical Engineering",
"Bachelor of Chemical Engineering",
"Master of Chemical Engineering",
"Bachelor of Environmental Engineering",
"Master of Environmental Engineering",
"Bachelor of Industrial Engineering",
"Master of Industrial Engineering",
"Bachelor of Robotics Engineering",
"Master of Robotics Engineering",
"Bachelor of Telecommunications Engineering",
"Master of Telecommunications Engineering",
"Bachelor of Petroleum Engineering",
"Master of Petroleum Engineering",
"Bachelor of Marine Engineering",
"Master of Marine Engineering",
"Bachelor of Mechatronics Engineering",
"Master of Mechatronics Engineering",
"Bachelor of Software Engineering",
"Master of Software Engineering",
"Bachelor of Nursing (B.Nurs)",
"Master of Nursing (MSN)",
"Bachelor of Medicine (MBBS)",
"Doctor of Medicine (MD)",
"Bachelor of Pharmacy (B.Pharm)",
"Master of Pharmacy (MPharm)",
"Bachelor of Public Health (BPH)",
"Master of Public Health (MPH)",
"Bachelor of Physiotherapy (BPT)",
"Master of Physiotherapy (MPT)",
"Bachelor of Occupational Therapy",
"Master of Occupational Therapy",
"Bachelor of Dentistry (BDS)",
"Master of Dentistry",
"Bachelor of Biomedical Science",
"Master of Biomedical Science",
"Bachelor of Radiology",
"Master of Radiology",
"Bachelor of Optometry",
"Master of Optometry",
"Bachelor of Veterinary Science (BVSc)",
"Master of Veterinary Science",
"Bachelor of Clinical Psychology",
"Master of Clinical Psychology",
"Bachelor of Nutrition and Dietetics",
"Master of Nutrition and Dietetics",
"Bachelor of Speech-Language Pathology",
"Master of Speech-Language Pathology",
"Bachelor of Genetic Counseling",
"Master of Genetic Counseling",
"Bachelor of Health Administration",
"Master of Health Administration",
"Bachelor of Health Sciences",
"Master of Health Sciences",
"Bachelor of Emergency Management",
"Master of Emergency Management",
"Bachelor of Computer Science (BSc CS)",
"Master of Computer Science (MSc CS)",
"Bachelor of Information Technology (B.IT)",
"Master of Information Technology (M.IT)",
"Bachelor of Software Engineering",
"Master of Software Engineering",
"Bachelor of Data Science",
"Master of Data Science",
"Bachelor of Artificial Intelligence",
"Master of Artificial Intelligence",
"Bachelor of Cybersecurity",
"Master of Cybersecurity",
"Bachelor of Network Engineering",
"Master of Network Engineering",
"Bachelor of Information Systems",
"Master of Information Systems",
"Bachelor of Cloud Computing",
"Master of Cloud Computing",
"Bachelor of Web Development",
"Master of Web Development",
"Bachelor of Mobile App Development",
"Master of Mobile App Development",
"Bachelor of Game Design",
"Master of Game Design",
"Bachelor of Information Security",
"Master of Information Security",
"Bachelor of Digital Media",
"Master of Digital Media",
"Bachelor of Computer Graphics",
"Master of Computer Graphics",
"Bachelor of Human-Computer Interaction",
"Master of Human-Computer Interaction",
"Bachelor of IT Management",
"Master of IT Management",
"Bachelor of Arts (BA)",
"Master of Arts (MA)",
"Bachelor of Fine Arts (BFA)",
"Master of Fine Arts (MFA)",
"Bachelor of English Literature",
"Master of English Literature",
"Bachelor of History",
"Master of History",
"Bachelor of Philosophy",
"Master of Philosophy",
"Bachelor of Sociology",
"Master of Sociology",
"Bachelor of Anthropology",
"Master of Anthropology",
"Bachelor of Political Science",
"Master of Political Science",
"Bachelor of Psychology",
"Master of Psychology",
"Bachelor of International Relations",
"Master of International Relations",
"Bachelor of Geography",
"Master of Geography",
"Bachelor of Economics",
"Master of Economics",
"Bachelor of Gender Studies",
"Master of Gender Studies",
"Bachelor of Criminology",
"Master of Criminology",
"Bachelor of Cultural Studies",
"Master of Cultural Studies",
"Bachelor of Communication",
"Master of Communication",
"Bachelor of Media Studies",
"Master of Media Studies",
"Bachelor of Journalism",
"Master of Journalism",
"Bachelor of Graphic Design",
"Master of Graphic Design",
"Bachelor of Performing Arts",
"Master of Performing Arts",
"Bachelor of Science (B.Sc)",
"Master of Science (M.Sc)",
"Bachelor of Physics",
"Master of Physics",
"Bachelor of Chemistry",
"Master of Chemistry",
"Bachelor of Biology",
"Master of Biology",
"Bachelor of Environmental Science",
"Master of Environmental Science",
"Bachelor of Geology",
"Master of Geology",
"Bachelor of Biochemistry",
"Master of Biochemistry",
"Bachelor of Microbiology",
"Master of Microbiology",
"Bachelor of Biotechnology",
"Master of Biotechnology",
"Bachelor of Genetics",
"Master of Genetics",
"Bachelor of Zoology",
"Master of Zoology",
"Bachelor of Botany",
"Master of Botany",
"Bachelor of Marine Biology",
"Master of Marine Biology",
"Bachelor of Ecology",
"Master of Ecology",
"Bachelor of Environmental Management",
"Master of Environmental Management",
"Bachelor of Laws (LLB)",
"Master of Laws (LLM)",
"Bachelor of Criminal Law",
"Master of Criminal Law",
"Bachelor of International Law",
"Master of International Law",
"Bachelor of Corporate Law",
"Master of Corporate Law",
"Bachelor of Human Rights Law",
"Master of Human Rights Law",
"Bachelor of Intellectual Property Law",
"Master of Intellectual Property Law",
"Bachelor of Taxation Law",
"Master of Taxation Law",
"Bachelor of Environmental Law",
"Master of Environmental Law",
"Bachelor of Labor Law",
"Master of Labor Law",
"Bachelor of Family Law",
"Master of Family Law",
"Bachelor of Immigration Law",
"Master of Immigration Law",
"Bachelor of Sports Law",
"Master of Sports Law",
"Bachelor of Maritime Law",
"Master of Maritime Law",
"Bachelor of Arbitration Law",
"Master of Arbitration Law",
"Bachelor of Civil Litigation",
"Master of Civil Litigation",
"Bachelor of Education (B.Ed)",
"Master of Education (M.Ed)",
"Bachelor of Early Childhood Education",
"Master of Early Childhood Education",
"Bachelor of Primary Education",
"Master of Primary Education",
"Bachelor of Secondary Education",
"Master of Secondary Education",
"Bachelor of Special Education",
"Master of Special Education",
"Bachelor of Educational Psychology",
"Master of Educational Psychology",
"Bachelor of Curriculum and Instruction",
"Master of Curriculum and Instruction",
"Bachelor of Educational Leadership",
"Master of Educational Leadership",
"Bachelor of Adult Education",
"Master of Adult Education",
"Bachelor of TESOL",
"Master of TESOL",
"Bachelor of Instructional Design",
"Master of Instructional Design",
"Bachelor of Literacy Education",
"Master of Literacy Education",
"Bachelor of Education Policy",
"Master of Education Policy",
"Bachelor of STEM Education",
"Master of STEM Education",
"Bachelor of Architecture (B.Arch)",
"Master of Architecture (M.Arch)",
"Bachelor of Interior Design",
"Master of Interior Design",
"Bachelor of Landscape Architecture",
"Master of Landscape Architecture"
 ]
  
  


export const popularCourses = [
"Bachelor’s in Financial Management",
"Accountancy, Finance, Banking",
"Bachelor’s in Actuarial Science",
"Bachelor’s in Agricultural Science",
"Bachelor's in Architecture Studies",
"Bachelors in Biomedical Engineering",
"Bachelor’s in Core Engineering",
"Bachelor of Earth Science",
"Bachelor of Computer Science",
"Bachelor of Psychology",
"Bachelor of Tourism & Hospitality Management",
"Bachelor of Engineering (In any Field)",
"Postgraduate Diploma & Bachelors of Agricultural Science & Forestry",
"Bachelor of Tourism",
"Bachelor of Hospitality Management",
"Master of Business Administration",
"Bachelor’s & Diplomas in Artificial Intelligence",
"Master of Professional Accounting",
"Bachelor of Sports Management",
"Bachelor of Information Technology & Computer Science",
"Bachelor of Design Innovation",
"Bachelor of Viticulture and Oenology",
]
