export const NOTIFICATION_TITLES = {
    // Agent Side
    OFFER_LETTER_APPROVED_AGENT: "Offer Letter Approved",
    OFFER_LETTER_REJECTED_AGENT: "Offer Letter Rejected",
    RECEIVED_OFFER_LETTER_AGENT: "Received Offer Letter",
    COURSE_FEE_APPROVED_AGENT: "Course Fee Approved",
    COURSE_FEE_REJECTED_AGENT: "Course Fee Rejected",
    VISA_LODGEMENT_APPROVED_AGENT: "Visa Lodgement Approved",
    VISA_LODGEMENT_REJECTED_AGENT: "Visa Lodgement Rejected",
    VISA_APPROVED_BY_EMBASSY_AGENT: "Visa Approved by Embassy",
    VISA_REJECTED_BY_EMBASSY_AGENT: "Visa Rejected by Embassy",
    TICKET_RESOLVED_AGENT: "Ticket Resolved",
    AGENT_WITHDRAWAL_COMPLETE : "AGENT_WITHDRAWAL_COMPLETE",
  
    // Student Side
    OFFER_LETTER_APPROVED_STUDENT: "Offer Letter Approved",
    OFFER_LETTER_REJECTED_STUDENT: "Offer Letter Rejected",
    RECEIVED_OFFER_LETTER_STUDENT: "Received Offer Letter",
    COURSE_FEE_APPROVED_STUDENT: "Course Fee Approved",
    COURSE_FEE_REJECTED_STUDENT: "Course Fee Rejected",
    VISA_LODGEMENT_APPROVED_STUDENT: "Visa Lodgement Approved",
    VISA_LODGEMENT_REJECTED_STUDENT: "Visa Lodgement Rejected",
    VISA_APPROVED_BY_EMBASSY_STUDENT: "Visa Approved by Embassy",
    VISA_REJECTED_BY_EMBASSY_STUDENT: "Visa Rejected by Embassy",
    TICKET_RESOLVED_STUDENT: "Ticket Resolved",
    STUDENT_WITHDRAWAL_COMPLETE: "STUDENT_WITHDRAWAL_COMPLETE",
  
    // Admin Side
    AGENT_REGISTERED_FOR_APPROVAL: "Agent Registered for Approval",
    STUDENT_REGISTERED_FOR_APPROVAL: "Student Registered for Approval",
    AGENT_PROFILE_DELETED_RE_REGISTERED: "Agent Profile Deleted and Re-Registered",
    STUDENT_PROFILE_DELETED_RE_REGISTERED: "Student Profile Deleted and Re-Registered",
    AGENT_SUBMITTED_OFFER_LETTER: "Agent Submitted Offer Letter Application",
    AGENT_SUBMITTED_COURSE_FEE: "Agent Submitted Course Fee Application",
    AGENT_SUBMITTED_VISA_LODGEMENT: "Agent Submitted Visa Lodgement Application",
    STUDENT_SUBMITTED_OFFER_LETTER: "Student Submitted Offer Letter Application",
    STUDENT_SUBMITTED_COURSE_FEE: "Student Submitted Course Fee Application",
    STUDENT_SUBMITTED_VISA_LODGEMENT: "Student Submitted Visa Lodgement Application",
    AGENT_RAISED_TICKET: "Agent Raised Ticket",
    STUDENT_RAISED_TICKET: "Student Raised Ticket",
    AGENT_RESUBMITTED_OFFER_LETTER: "Agent Resubmitted Offer Letter Application",
    AGENT_RESUBMITTED_COURSE_FEE: "Agent Resubmitted Course Fee Application",
    AGENT_RESUBMITTED_VISA_LODGEMENT: "Agent Resubmitted Visa Lodgement Application",
    STUDENT_RESUBMITTED_OFFER_LETTER: "Student Resubmitted Offer Letter Application",
    STUDENT_RESUBMITTED_COURSE_FEE: "Student Resubmitted Course Fee Application",
    STUDENT_RESUBMITTED_VISA_LODGEMENT: "Student Resubmitted Visa Lodgement Application",
    AGENT_REQUESTED_AMOUNT_WITHDRAWAL: "Agent Requested Amount Withdrawal",
    STUDENT_REQUESTED_AMOUNT_WITHDRAWAL: "Student Requested Amount Withdrawal",
    AGENT_STUDENT_VISA_STAMP: "Students by Agent Stamp",
    STUDENT_STUDENT_VISA_STAMP: "Students by Student Stamp",
    DEFERMATION_BY_AGENT : "",
    DEFERMATION_BY_STUDENT : ""
  };
  